### ISSUE TITLE
Helm charts voor Objects en Objecttypes API

### ISSUE THREAD

**Issue by Hugo-ter-Doest** [maykinmedia/charts#10]
In de repo's van Objects en Object types staan ook Helm charts, maar zijn al ouder. Welke kunnen we het beste gebruiken voor installatie bij SSC Enschede op Azure AKS?

(overigens fijn dat jullie Helm charts maken voor al deze componenten)

**Comment by sjoerdie** [comment]
Je kan het beste de charts gebruiken uit deze repo.

**Comment by Hugo-ter-Doest** [comment]
Dank!
