### ISSUE TITLE
Open Inwoner chart, toevoegen persistent ES

### ISSUE THREAD

**Issue by alextreme** [maykinmedia/charts#124]
n.a.v. Taiga Dimpact 107

https://github.com/maykinmedia/charts/blob/02f0814739147a55a842036ae9cfd6ae7a999381/charts/openinwoner/values.yaml#L355

> Dus de PVC voor master en data op true zetten. Ik neem dat mee in de volgende chart release, voor nu kan SSC deze overrulen in haar eigen values.yml (wat ze al doen).

**Comment by sjoerdie** [comment]
https://github.com/maykinmedia/charts/pull/126
